
Neos:
  Neos:
    Ui:
      resources:
        javascript:

          'Neos.Neos.UI.ExtensibilityExamples:CustomStylingForCkEditor':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/CustomStylingForCkEditor/Plugin.js

          'Neos.Neos.UI.ExtensibilityExamples:CustomEditor':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/CustomEditor/Plugin.js