
Neos:
  Neos:
    Ui:
      resources:
        javascript:

          'Neos.Neos.UI.ExtensibilityExamples:CustomStylingForCkEditor':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/CustomStylingForCkEditor/Plugin.js

          'Neos.Neos.UI.ExtensibilityExamples:CustomEditor':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/CustomEditor/Plugin.js

          'Neos.Neos.UI.ExtensibilityExamples:ColorPickerEditor':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/ColorPickerEditor/Plugin.js

          'Neos.Neos.UI.ExtensibilityExamples:ReplacingComponentsViaUnplannedExtensibility':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/ReplacingComponentsViaUnplannedExtensibility/Plugin.js

          'Neos.Neos.UI.ExtensibilityExamples:AdjustedImageEditor':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/AdjustedImageEditor/Plugin.js


        stylesheets:

          'Neos.Neos.UI.ExtensibilityExamples:ReplacingComponentsViaUnplannedExtensibility':
            resource: resource://Neos.Neos.UI.ExtensibilityExamples/Public/ReplacingComponentsViaUnplannedExtensibility/Plugin.css